/* tslint:disable */
/* eslint-disable */
/**
 * Cart
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductToJSON,
} from '../models';

export interface ShowProductByIdRequest {
    productId: string;
}

/**
 * 
 */
export class ProductApi extends runtime.BaseAPI {

    /**
     * Info for a specific product
     */
    async showProductByIdRaw(requestParameters: ShowProductByIdRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Product>> {
        if (requestParameters.productId === null || requestParameters.productId === undefined) {
            throw new runtime.RequiredError('productId','Required parameter requestParameters.productId was null or undefined when calling showProductById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products/{productId}`.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters.productId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductFromJSON(jsonValue));
    }

    /**
     * Info for a specific product
     */
    async showProductById(requestParameters: ShowProductByIdRequest, initOverrides?: RequestInit): Promise<Product> {
        const response = await this.showProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
